// Embed the Wadi DSL examples + reference docs into a generated TS module, so the
// bundled MCP server is fully self-contained — an agent with ONLY this server can
// author correct .wdl (no repo checkout, no separate skill files). Run before dev
// and build. Output (src/assets.generated.ts) is gitignored.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "..", ".."); // wadi-mcp/scripts -> wadi-mcp -> repo root

// name -> repo-relative path
const EXAMPLES = {
  minimal: "wadi-dsl/examples/minimal.wdl",
  two_room: "wadi-dsl/examples/two_room.wdl",
  two_story: "wadi-dsl/examples/two_story.wdl",
  coastal: "wadi-dsl/examples/coastal.wdl",
  complete: "wadi-dsl/examples/complete.wdl",
};

// doc id -> { path, title }
const DOCS = {
  guide: { path: "wadi-skill/architect/SKILL.md", title: "How to author a Wadi house (the workflow)" },
  dsl: { path: "wadi-skill/architect/reference/dsl.md", title: "The Wadi DSL (.wdl) — syntax reference" },
  conventions: { path: "wadi-skill/architect/reference/conventions.md", title: "Structural coding conventions (C1/C2/C3…)" },
  "coordinate-system": { path: "wadi-skill/architect/reference/coordinate-system.md", title: "Coordinates, units & the centreline convention" },
  "parametric-conventions": { path: "wadi-skill/architect/reference/parametric-conventions.md", title: "Building a fully-parametric template" },
  "roof-v2-guide": { path: "wadi-skill/architect/reference/roof-v2-guide.md", title: "The roof object (hip/gable/shed/flat)" },
  "data-model": { path: "wadi-skill/architect/reference/data-model.md", title: "The underlying .wadi schema (generated from Zod)" },
};

function read(rel) {
  const abs = resolve(REPO, rel);
  if (!existsSync(abs)) {
    console.warn(`gen-assets: WARNING missing ${rel} — skipping`);
    return null;
  }
  return readFileSync(abs, "utf8");
}

const examples = {};
for (const [name, rel] of Object.entries(EXAMPLES)) {
  const t = read(rel);
  if (t != null) examples[name] = t;
}

const docs = {};
for (const [id, { path, title }] of Object.entries(DOCS)) {
  const t = read(path);
  if (t != null) docs[id] = { title, body: t };
}

const banner = "// GENERATED by scripts/gen-assets.mjs — do not edit. Run `npm run gen-assets`.\n";
const out =
  banner +
  `export const EXAMPLES: Record<string, string> = ${JSON.stringify(examples, null, 2)};\n\n` +
  `export const DOCS: Record<string, { title: string; body: string }> = ${JSON.stringify(docs, null, 2)};\n`;

const dest = resolve(HERE, "..", "src", "assets.generated.ts");
writeFileSync(dest, out);
console.error(
  `gen-assets: wrote ${Object.keys(examples).length} examples + ${Object.keys(docs).length} docs -> src/assets.generated.ts`,
);
